version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: backend/deploy/Dockerfile
    image: triolingo-backend
    ports:
      - "5000:80"

  frontend:
    build:
      context: .
      dockerfile: frontend/deploy/Dockerfile
    image: triolingo-frontend
    ports:
      - "80:80"

