version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: deploy/Dockerfile
    image: triolingo-backend
    ports:
      - "5000:80"

  frontend:
    build:
      context: ./frontend
      dockerfile: deploy/Dockerfile
    image: triolingo-frontend
    ports:
      - "80:80"

